// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controlresponsepoint.proto

package control

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ControlResponsePoint struct {
	RequestId            *string  `protobuf:"bytes,1,req,name=requestId" json:"requestId,omitempty"`
	MessageId            *string  `protobuf:"bytes,2,req,name=messageId" json:"messageId,omitempty"`
	RequestMethod        *string  `protobuf:"bytes,3,req,name=requestMethod" json:"requestMethod,omitempty"`
	CallType             *string  `protobuf:"bytes,4,req,name=callType" json:"callType,omitempty"`
	ControlChannelId     *string  `protobuf:"bytes,5,req,name=controlChannelId" json:"controlChannelId,omitempty"`
	ProductKey           *string  `protobuf:"bytes,6,req,name=productKey" json:"productKey,omitempty"`
	DeviceKey            *string  `protobuf:"bytes,7,req,name=deviceKey" json:"deviceKey,omitempty"`
	AssetId              *string  `protobuf:"bytes,8,req,name=assetId" json:"assetId,omitempty"`
	ServiceName          *string  `protobuf:"bytes,9,req,name=serviceName" json:"serviceName,omitempty"`
	ServiceId            *string  `protobuf:"bytes,10,req,name=serviceId" json:"serviceId,omitempty"`
	CallbackUrl          *string  `protobuf:"bytes,11,req,name=callbackUrl" json:"callbackUrl,omitempty"`
	InputData            *string  `protobuf:"bytes,12,req,name=inputData" json:"inputData,omitempty"`
	OutputData           *string  `protobuf:"bytes,13,req,name=outputData" json:"outputData,omitempty"`
	Status               *int64   `protobuf:"varint,14,req,name=status" json:"status,omitempty"`
	Msg                  *string  `protobuf:"bytes,15,req,name=msg" json:"msg,omitempty"`
	Submsg               *string  `protobuf:"bytes,16,req,name=submsg" json:"submsg,omitempty"`
	Timeout              *int64   `protobuf:"varint,17,req,name=timeout" json:"timeout,omitempty"`
	GmtServiceRequest    *int64   `protobuf:"varint,18,req,name=gmtServiceRequest" json:"gmtServiceRequest,omitempty"`
	GmtServiceReply      *int64   `protobuf:"varint,19,req,name=gmtServiceReply" json:"gmtServiceReply,omitempty"`
	GmtDeviceReply       *int64   `protobuf:"varint,20,req,name=gmtDeviceReply" json:"gmtDeviceReply,omitempty"`
	Attr                 *string  `protobuf:"bytes,21,opt,name=attr" json:"attr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlResponsePoint) Reset()         { *m = ControlResponsePoint{} }
func (m *ControlResponsePoint) String() string { return proto.CompactTextString(m) }
func (*ControlResponsePoint) ProtoMessage()    {}
func (*ControlResponsePoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e31e744205292d, []int{0}
}

func (m *ControlResponsePoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlResponsePoint.Unmarshal(m, b)
}
func (m *ControlResponsePoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlResponsePoint.Marshal(b, m, deterministic)
}
func (m *ControlResponsePoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlResponsePoint.Merge(m, src)
}
func (m *ControlResponsePoint) XXX_Size() int {
	return xxx_messageInfo_ControlResponsePoint.Size(m)
}
func (m *ControlResponsePoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlResponsePoint.DiscardUnknown(m)
}

var xxx_messageInfo_ControlResponsePoint proto.InternalMessageInfo

func (m *ControlResponsePoint) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *ControlResponsePoint) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *ControlResponsePoint) GetRequestMethod() string {
	if m != nil && m.RequestMethod != nil {
		return *m.RequestMethod
	}
	return ""
}

func (m *ControlResponsePoint) GetCallType() string {
	if m != nil && m.CallType != nil {
		return *m.CallType
	}
	return ""
}

func (m *ControlResponsePoint) GetControlChannelId() string {
	if m != nil && m.ControlChannelId != nil {
		return *m.ControlChannelId
	}
	return ""
}

func (m *ControlResponsePoint) GetProductKey() string {
	if m != nil && m.ProductKey != nil {
		return *m.ProductKey
	}
	return ""
}

func (m *ControlResponsePoint) GetDeviceKey() string {
	if m != nil && m.DeviceKey != nil {
		return *m.DeviceKey
	}
	return ""
}

func (m *ControlResponsePoint) GetAssetId() string {
	if m != nil && m.AssetId != nil {
		return *m.AssetId
	}
	return ""
}

func (m *ControlResponsePoint) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *ControlResponsePoint) GetServiceId() string {
	if m != nil && m.ServiceId != nil {
		return *m.ServiceId
	}
	return ""
}

func (m *ControlResponsePoint) GetCallbackUrl() string {
	if m != nil && m.CallbackUrl != nil {
		return *m.CallbackUrl
	}
	return ""
}

func (m *ControlResponsePoint) GetInputData() string {
	if m != nil && m.InputData != nil {
		return *m.InputData
	}
	return ""
}

func (m *ControlResponsePoint) GetOutputData() string {
	if m != nil && m.OutputData != nil {
		return *m.OutputData
	}
	return ""
}

func (m *ControlResponsePoint) GetStatus() int64 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ControlResponsePoint) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *ControlResponsePoint) GetSubmsg() string {
	if m != nil && m.Submsg != nil {
		return *m.Submsg
	}
	return ""
}

func (m *ControlResponsePoint) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

func (m *ControlResponsePoint) GetGmtServiceRequest() int64 {
	if m != nil && m.GmtServiceRequest != nil {
		return *m.GmtServiceRequest
	}
	return 0
}

func (m *ControlResponsePoint) GetGmtServiceReply() int64 {
	if m != nil && m.GmtServiceReply != nil {
		return *m.GmtServiceReply
	}
	return 0
}

func (m *ControlResponsePoint) GetGmtDeviceReply() int64 {
	if m != nil && m.GmtDeviceReply != nil {
		return *m.GmtDeviceReply
	}
	return 0
}

func (m *ControlResponsePoint) GetAttr() string {
	if m != nil && m.Attr != nil {
		return *m.Attr
	}
	return ""
}

type ControlResponsePoints struct {
	Points               []*ControlResponsePoint `protobuf:"bytes,1,rep,name=points" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ControlResponsePoints) Reset()         { *m = ControlResponsePoints{} }
func (m *ControlResponsePoints) String() string { return proto.CompactTextString(m) }
func (*ControlResponsePoints) ProtoMessage()    {}
func (*ControlResponsePoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e31e744205292d, []int{1}
}

func (m *ControlResponsePoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlResponsePoints.Unmarshal(m, b)
}
func (m *ControlResponsePoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlResponsePoints.Marshal(b, m, deterministic)
}
func (m *ControlResponsePoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlResponsePoints.Merge(m, src)
}
func (m *ControlResponsePoints) XXX_Size() int {
	return xxx_messageInfo_ControlResponsePoints.Size(m)
}
func (m *ControlResponsePoints) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlResponsePoints.DiscardUnknown(m)
}

var xxx_messageInfo_ControlResponsePoints proto.InternalMessageInfo

func (m *ControlResponsePoints) GetPoints() []*ControlResponsePoint {
	if m != nil {
		return m.Points
	}
	return nil
}

func init() {
	proto.RegisterType((*ControlResponsePoint)(nil), "controlresponsedata.ControlResponsePoint")
	proto.RegisterType((*ControlResponsePoints)(nil), "controlresponsedata.ControlResponsePoints")
}

func init() { proto.RegisterFile("controlresponsepoint.proto", fileDescriptor_98e31e744205292d) }

var fileDescriptor_98e31e744205292d = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x49, 0x5c, 0xd2, 0x7a, 0xdc, 0xe6, 0x8f, 0xdd, 0x94, 0x81, 0x93, 0xd5, 0x93, 0xb9,
	0x18, 0x89, 0x1b, 0xd7, 0xb6, 0x17, 0x0b, 0x81, 0xaa, 0x00, 0x1f, 0x60, 0xe3, 0x1d, 0x1c, 0x0b,
	0xdb, 0x6b, 0x76, 0x67, 0x91, 0xf2, 0xb9, 0xf8, 0x82, 0x68, 0xd7, 0x36, 0xa0, 0x28, 0xc7, 0xfd,
	0xbd, 0x37, 0x9a, 0xa7, 0x79, 0x0b, 0x6f, 0x4a, 0xd5, 0xb1, 0x56, 0x8d, 0x26, 0xd3, 0xab, 0xce,
	0x50, 0xaf, 0xea, 0x8e, 0xf3, 0x5e, 0x2b, 0x56, 0x71, 0x72, 0xa2, 0x49, 0xc1, 0xe2, 0xfe, 0x77,
	0x00, 0xb7, 0x8f, 0x03, 0xdf, 0x8d, 0xfc, 0xd9, 0xcd, 0xc4, 0x1b, 0x08, 0x35, 0xfd, 0xb4, 0x64,
	0xb8, 0x90, 0x38, 0x4b, 0xe7, 0x59, 0xe8, 0x50, 0x4b, 0xc6, 0x88, 0x8a, 0x0a, 0x89, 0x73, 0x8f,
	0xb6, 0x70, 0x33, 0xba, 0x3e, 0x11, 0x1f, 0x94, 0xc4, 0xc0, 0xe3, 0x35, 0x5c, 0x95, 0xa2, 0x69,
	0xbe, 0x1e, 0x7b, 0xc2, 0x0b, 0x4f, 0x10, 0xd6, 0xe3, 0xfa, 0xc7, 0x83, 0xe8, 0x3a, 0x6a, 0x0a,
	0x89, 0x2f, 0xbd, 0x12, 0x03, 0xf4, 0x5a, 0x49, 0x5b, 0xf2, 0x47, 0x3a, 0xe2, 0x62, 0xda, 0x24,
	0xe9, 0x57, 0x5d, 0x92, 0x43, 0x97, 0x1e, 0xad, 0xe0, 0x52, 0x18, 0x43, 0x2e, 0xcd, 0x95, 0x07,
	0x09, 0x44, 0x86, 0xb4, 0x33, 0x7d, 0x16, 0x2d, 0x61, 0x38, 0x0d, 0x8e, 0xb0, 0x90, 0x08, 0x93,
	0xcf, 0x65, 0xd9, 0x8b, 0xf2, 0xc7, 0x37, 0xdd, 0x60, 0x34, 0xf9, 0xea, 0xae, 0xb7, 0xfc, 0x24,
	0x58, 0xe0, 0xf5, 0x94, 0x43, 0x59, 0x9e, 0xd8, 0x8d, 0x67, 0x4b, 0x58, 0x18, 0x16, 0x6c, 0x0d,
	0x2e, 0xd3, 0x79, 0x16, 0xc4, 0x11, 0x04, 0xad, 0xa9, 0x70, 0xf5, 0x57, 0xb4, 0x7b, 0xf7, 0x5e,
	0x4f, 0x09, 0xb9, 0x6e, 0x49, 0x59, 0xc6, 0x8d, 0x77, 0xbf, 0x86, 0x4d, 0xd5, 0xf2, 0x97, 0x21,
	0xcf, 0x6e, 0x38, 0x13, 0xc6, 0x5e, 0x7a, 0x05, 0xab, 0xff, 0xa5, 0xbe, 0x39, 0x62, 0xe2, 0x85,
	0x3b, 0x58, 0x56, 0x2d, 0x3f, 0xd1, 0x3f, 0x7e, 0xeb, 0xf9, 0x35, 0x5c, 0x08, 0x66, 0x8d, 0xdb,
	0x74, 0x96, 0x85, 0xf7, 0x3b, 0xd8, 0x9e, 0x2b, 0xcd, 0xc4, 0x1f, 0x60, 0xe1, 0x2b, 0x37, 0x38,
	0x4b, 0x83, 0x2c, 0x7a, 0xff, 0x36, 0x3f, 0x53, 0x7a, 0x7e, 0x6e, 0xf6, 0xe1, 0x1d, 0xdc, 0x95,
	0xaa, 0x1d, 0xfe, 0xca, 0xde, 0x7e, 0xcf, 0x2b, 0xea, 0x48, 0x0b, 0x26, 0xf9, 0x90, 0x9c, 0xf8,
	0xdd, 0x81, 0x9e, 0x5f, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x65, 0xd2, 0xd2, 0xb7, 0x6c, 0x02,
	0x00, 0x00,
}
